version: '3.1'

services:

  db:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jina_search
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin
    restart: always
    ports:
      - 5050:80
    environment:
      #- PGADMIN_LISTEN_ADDRESS=0.0.0.0
      #- PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - db

